import type { Metadata } from "next";

import Providers from "./_providers";

export const metadata: Metadata = {
  title: "React Aria Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
